# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 18c2f44b71d5ff614c512bcd5103a478aed8837886a8895250cf0a952acb5641f23ed9188fbd0d7281b24a1b1109d6fa15aa27df893ae235e6de30cd306c8e23

test:
  secret_key_base: 53a43014558ba1291c0a2daeea02e28464439c2eb3000b7a5cf92616f1ed8f795eed5c2d4a346bcbedd99197caffe01ceb2b2e2797bac529ed605c461c2f0104

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
